
import java.io.File;
import java.io.IOException;
import java.lang.String;
import java.util.Scanner;
import java.util.Vector;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Highscores.java
 *
 * Created on Aug 12, 2011, 11:13:57 PM
 */
/**
 *
 * @author n1ck
 */
// TODO: Implement this class
public class Highscores extends javax.swing.JPanel {
    private Vector<String> score = new Vector<String>();
    /** Creates new form Highscores */
    public Highscores() {
        initComponents();
         String path = "C:\\Users\\n1ck\\Documents\\NetBeansProjects\\ASL\\ASL\\src\\highscores.txt";
         File file = new File(path);
         try{
              Scanner filein = new Scanner(file);
              while(filein.hasNext()){
                  score.add(filein.nextLine());
                  
              }
              scoresList.setListData(score);
         }
         catch(IOException e){
             System.err.println("Error loading highscores file");
         }
        
    }
    public boolean addHighscore(String initials, int s){
        if(initials.length() > 3) return false;
        if(s > 999) return false;
        score.add(initials+" "+s);
        scoresList.setListData(score);
        return true;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoresList = new javax.swing.JList();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("HIGHSCORES");

        scoresList.setBackground(new java.awt.Color(0, 0, 0));
        scoresList.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        scoresList.setForeground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(scoresList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList scoresList;
    // End of variables declaration//GEN-END:variables
}
