
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * labels.java
 *
 * Created on Jul 29, 2011, 2:21:00 AM
 */
/**
 *
 * @author n1ck
 */
public class labels extends javax.swing.JPanel {
    private boolean cheat= false;
    /** Creates new form labels */
    public labels() {
        initComponents();
    }

    public void setReplaysNumberLabel(String replaysNumberLabel) {
        this.replaysNumberLabel.setText(replaysNumberLabel);
    }

    public void setScoreText(String scoreText) {
        this.scoreText.setText(scoreText);
    }
    public void setCheatText(String cheatText){
        this.cheatLabel.setText(cheatText);
    }
    public void enableCheatMode(){
        cheat = true;
        cheatLabel.setEnabled(true);
    }
    public void disableCheatMode(){
        cheat = false;
        cheatLabel.setEnabled(false);
        cheatLabel.setText("");
    }
    public boolean cheatModeEnabled(){return cheat;}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replaysNumberLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        scoreText = new javax.swing.JTextField();
        replaysLabel = new javax.swing.JLabel();
        cheatLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        replaysNumberLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        replaysNumberLabel.setForeground(new java.awt.Color(102, 255, 0));
        replaysNumberLabel.setText("0");

        scoreLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        scoreLabel.setForeground(new java.awt.Color(255, 0, 0));
        scoreLabel.setText("Score");

        scoreText.setBackground(new java.awt.Color(204, 204, 204));
        scoreText.setEditable(false);
        scoreText.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        scoreText.setForeground(new java.awt.Color(255, 0, 0));
        scoreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        scoreText.setText("0");
        scoreText.setBorder(null);
        scoreText.setOpaque(false);

        replaysLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        replaysLabel.setForeground(new java.awt.Color(51, 255, 51));
        replaysLabel.setText("Replays");

        cheatLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        cheatLabel.setForeground(new java.awt.Color(204, 0, 255));
        cheatLabel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(replaysLabel)
                .addGap(36, 36, 36)
                .addComponent(replaysNumberLabel)
                .addGap(32, 32, 32)
                .addComponent(cheatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(scoreLabel)
                .addComponent(replaysLabel)
                .addComponent(replaysNumberLabel)
                .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(cheatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cheatLabel;
    private javax.swing.JLabel replaysLabel;
    private javax.swing.JLabel replaysNumberLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JTextField scoreText;
    // End of variables declaration//GEN-END:variables
}
