
import javax.swing.JOptionPane;






/*
 * TitleFrame.java
 *
 * Created on Jul 27, 2011, 1:35:38 AM
 */
/**
 *
 * @author n1ck
 */
public class TitleFrame extends javax.swing.JFrame {
    private ViewController vc;
    private boolean[] units = new boolean[12];
    public TitleFrame(ViewController v) {
       vc = v;
       vc.setTitleFrame(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGame = new javax.swing.JButton();
        unit13Check = new javax.swing.JCheckBox();
        unit14Check = new javax.swing.JCheckBox();
        unit15Check = new javax.swing.JCheckBox();
        unit16Check = new javax.swing.JCheckBox();
        unit17Check = new javax.swing.JCheckBox();
        unit18Check = new javax.swing.JCheckBox();
        unit19Check = new javax.swing.JCheckBox();
        unit20Check = new javax.swing.JCheckBox();
        unit21Check = new javax.swing.JCheckBox();
        unit22Check = new javax.swing.JCheckBox();
        unit23Check = new javax.swing.JCheckBox();
        unit24Check = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ASL Video Flashcards");
        setBackground(new java.awt.Color(0, 0, 0));

        startGame.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        startGame.setText("Start");
        startGame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startGameMouseClicked(evt);
            }
        });

        unit13Check.setText("Unit 13");
        unit13Check.setBorder(new javax.swing.border.MatteBorder(null));

        unit14Check.setText("Unit 14");

        unit15Check.setText("Unit 15");

        unit16Check.setText("Unit 16");

        unit17Check.setText("Unit 17");

        unit18Check.setText("Unit 18");

        unit19Check.setText("Unit 19");

        unit20Check.setText("Unit 20");

        unit21Check.setText("Unit 21");

        unit22Check.setText("Unit 22");

        unit23Check.setText("Unit 23");

        unit24Check.setText("Unit 24");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setText("Select Units:");

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton1.setText("Quit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Viner Hand ITC", 2, 36)); // NOI18N
        jTextPane1.setText("ASL Video Flashcards!");
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(unit18Check)
                                .addComponent(unit17Check)
                                .addComponent(unit16Check)
                                .addComponent(unit15Check)
                                .addComponent(unit14Check))
                            .addComponent(unit13Check))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit20Check)
                            .addComponent(unit19Check)
                            .addComponent(unit21Check)
                            .addComponent(unit22Check)
                            .addComponent(unit23Check)
                            .addComponent(unit24Check))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unit19Check)
                            .addComponent(unit13Check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unit20Check)
                            .addComponent(unit14Check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unit21Check)
                            .addComponent(unit15Check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unit16Check)
                            .addComponent(unit22Check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unit17Check)
                            .addComponent(unit23Check)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit18Check)
                    .addComponent(unit24Check))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(startGame, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startGameMouseClicked
        
        setUnits();
        if(atLeastOne(units)){
            vc.switchStates();
        }
        
    }//GEN-LAST:event_startGameMouseClicked
    public boolean[] getUnits(){return units;}
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked
    //Need to reuse game frame
    private void setUnits(){
        units[0] = unit13Check.isSelected();
        units[1] = unit14Check.isSelected();
        units[2] = unit15Check.isSelected();
        units[3] = unit16Check.isSelected();
        units[4] = unit17Check.isSelected();
        units[5] = unit18Check.isSelected();
        units[6] = unit19Check.isSelected();
        units[7] = unit20Check.isSelected();
        units[8] = unit21Check.isSelected();
        units[9] = unit22Check.isSelected();
        units[10] = unit23Check.isSelected();
        units[11] = unit24Check.isSelected();
    }
     /**
     * Computes if at least one check box is selected
     * @param u
     * @return 
     */
    private boolean atLeastOne(boolean[] u){
        for(int i=0; i < u.length; ++i){
            if(u[i] == true) return true;
        }
        JOptionPane.showMessageDialog(this,"At least one unit must be selected!","Error!",JOptionPane.ERROR_MESSAGE);
        return false;
    }
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton startGame;
    private javax.swing.JCheckBox unit13Check;
    private javax.swing.JCheckBox unit14Check;
    private javax.swing.JCheckBox unit15Check;
    private javax.swing.JCheckBox unit16Check;
    private javax.swing.JCheckBox unit17Check;
    private javax.swing.JCheckBox unit18Check;
    private javax.swing.JCheckBox unit19Check;
    private javax.swing.JCheckBox unit20Check;
    private javax.swing.JCheckBox unit21Check;
    private javax.swing.JCheckBox unit22Check;
    private javax.swing.JCheckBox unit23Check;
    private javax.swing.JCheckBox unit24Check;
    // End of variables declaration//GEN-END:variables
}
